/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Business.Customer.CustomerDirectory;
import Business.DB4OUtil.DB4OUtil;
import Business.Database.DatabaseConnection;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Restaurant.RestaurantDirectory;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import UserInterface.AboutUs.AboutUsPanel;
import UserInterface.CustomerRole.RegisterPanel;
import UserInterface.RestaurantAdminRole.AdminWorkAreaPanel;
import UserInterface.SystemAdminWorkArea.ManageCustomers;
import java.awt.CardLayout;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author srikr
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private UserAccount userAccount;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    RestaurantDirectory restaurantDirectory; 
    CustomerDirectory customerDirectory;
    DeliveryManDirectory deliveryManDirectory;
    JPanel userProcessContainer;
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    public MainFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        
        con = DatabaseConnection.getCon();
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
        //this.setSize(1000, 650);
        restaurantDirectory = new RestaurantDirectory();
        customerDirectory = new CustomerDirectory();
        deliveryManDirectory = new DeliveryManDirectory();
        //backroundbtn.setIcon(new ImageIcon(new ImageIcon("4.png").getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT)));
    }

        public MainFrame(EcoSystem system) {
        initComponents();
        //system = dB4OUtil.retrieveSystem();
        dB4OUtil.storeSystem(system);
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        
        //con = DatabaseConnection.getCon();
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
        //this.setSize(1000, 650);
        //restaurantDirectory = new RestaurantDirectory();
        //customerDirectory = new CustomerDirectory();
        //deliveryManDirectory = new DeliveryManDirectory();
        
        //backroundbtn.setIcon(new ImageIcon(new ImageIcon("4.png").getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        JLeftPanel = new javax.swing.JPanel();
        Usernamelbl = new javax.swing.JLabel();
        Usernametxt = new javax.swing.JTextField();
        Passwordlbl = new javax.swing.JLabel();
        Passwordtxt = new javax.swing.JPasswordField();
        Loginbtn = new javax.swing.JButton();
        Logoutbtn = new javax.swing.JButton();
        Registerbtn = new javax.swing.JButton();
        txtNewuser = new javax.swing.JLabel();
        Homebtn = new javax.swing.JButton();
        Refreshbtn = new javax.swing.JButton();
        Exitbtn = new javax.swing.JButton();
        jRightPanel = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        MainHeadinglbl = new javax.swing.JLabel();
        backroundbtn = new javax.swing.JButton();
        Welcomelbl = new javax.swing.JLabel();
        Aboutbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLeftPanel.setBackground(new java.awt.Color(255, 255, 153));

        Usernamelbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Usernamelbl.setText("User Name");

        Passwordlbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Passwordlbl.setText("Password");

        Loginbtn.setBackground(new java.awt.Color(0, 0, 0));
        Loginbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        Loginbtn.setText("Sign in");
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnActionPerformed(evt);
            }
        });

        Logoutbtn.setBackground(new java.awt.Color(0, 0, 0));
        Logoutbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        Logoutbtn.setText("Sign Out");
        Logoutbtn.setEnabled(false);
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });

        Registerbtn.setBackground(new java.awt.Color(0, 0, 0));
        Registerbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        Registerbtn.setText("Sign Up");
        Registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbtnActionPerformed(evt);
            }
        });

        txtNewuser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNewuser.setText("New Here?");

        Homebtn.setBackground(new java.awt.Color(0, 0, 0));
        Homebtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Homebtn.setForeground(new java.awt.Color(255, 255, 255));
        Homebtn.setText("Home");
        Homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebtnActionPerformed(evt);
            }
        });

        Refreshbtn.setBackground(new java.awt.Color(0, 0, 0));
        Refreshbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Refreshbtn.setForeground(new java.awt.Color(255, 255, 255));
        Refreshbtn.setText("Refresh");
        Refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbtnActionPerformed(evt);
            }
        });

        Exitbtn.setBackground(new java.awt.Color(0, 0, 0));
        Exitbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        Exitbtn.setText("Exit");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JLeftPanelLayout = new javax.swing.GroupLayout(JLeftPanel);
        JLeftPanel.setLayout(JLeftPanelLayout);
        JLeftPanelLayout.setHorizontalGroup(
            JLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Usernametxt)
            .addComponent(Passwordtxt)
            .addGroup(JLeftPanelLayout.createSequentialGroup()
                .addGroup(JLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Passwordlbl)
                    .addComponent(Usernamelbl)
                    .addComponent(Loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewuser))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        JLeftPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Homebtn, Loginbtn, Logoutbtn, Registerbtn});

        JLeftPanelLayout.setVerticalGroup(
            JLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLeftPanelLayout.createSequentialGroup()
                .addComponent(Homebtn)
                .addGap(106, 106, 106)
                .addComponent(Usernamelbl)
                .addGap(6, 6, 6)
                .addComponent(Usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Passwordlbl)
                .addGap(6, 6, 6)
                .addComponent(Passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Loginbtn)
                .addGap(12, 12, 12)
                .addComponent(Logoutbtn)
                .addGap(30, 30, 30)
                .addComponent(txtNewuser)
                .addGap(6, 6, 6)
                .addComponent(Registerbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(Refreshbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exitbtn))
        );

        JLeftPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Homebtn, Loginbtn, Logoutbtn, Registerbtn});

        JLeftPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Passwordlbl, txtNewuser});

        jSplitPane.setLeftComponent(JLeftPanel);

        jRightPanel.setBackground(new java.awt.Color(255, 255, 153));
        jRightPanel.setLayout(new java.awt.CardLayout());

        WelcomePanel.setBackground(new java.awt.Color(255, 255, 153));

        MainHeadinglbl.setBackground(new java.awt.Color(255, 255, 153));
        MainHeadinglbl.setFont(new java.awt.Font("Onyx", 1, 90)); // NOI18N
        MainHeadinglbl.setText("SHARE TO EAT");

        backroundbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4.png"))); // NOI18N
        backroundbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backroundbtnActionPerformed(evt);
            }
        });

        Welcomelbl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Welcomelbl.setText("WELCOME");

        Aboutbtn.setBackground(new java.awt.Color(0, 0, 0));
        Aboutbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Aboutbtn.setForeground(new java.awt.Color(255, 255, 255));
        Aboutbtn.setText("Our Leadership");
        Aboutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backroundbtn)
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(MainHeadinglbl)
                            .addComponent(Welcomelbl))
                        .addGap(359, 359, 359)
                        .addComponent(Aboutbtn)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainHeadinglbl)
                    .addComponent(Aboutbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Welcomelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backroundbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jRightPanel.add(WelcomePanel, "card2");

        jSplitPane.setRightComponent(jRightPanel);

        getContentPane().add(jSplitPane, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed
        // Get user name
        String userName = Usernametxt.getText();
        char[] passwordCharArray = Passwordtxt.getPassword();
        String password = String.valueOf(passwordCharArray);

        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);

        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }else{
            CardLayout layout = (CardLayout)jRightPanel.getLayout();
            jRightPanel.add("workArea",userAccount.getRole().createWorkArea(jRightPanel, userAccount, system));
            layout.next(jRightPanel);
        }

        Loginbtn.setEnabled(false);
        Logoutbtn.setEnabled(true);
        Usernametxt.setEnabled(false);
        Passwordtxt.setEnabled(false);
    }//GEN-LAST:event_LoginbtnActionPerformed

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        Logoutbtn.setEnabled(false);
        Usernametxt.setEnabled(true);
        Passwordtxt.setEnabled(true);
        Loginbtn.setEnabled(true);

        Usernametxt.setText("");
        Passwordtxt.setText("");

        jRightPanel.removeAll();
        MainFrame mainframe = new MainFrame(system);
        mainframe.show();
        dispose();
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void RegisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)jRightPanel.getLayout();
        RegisterPanel rp = new RegisterPanel(userProcessContainer, system);
        //userProcessContainer.add("RegisterPanel", rp);
        //layout.next(userProcessContainer);
        jSplitPane.setRightComponent(rp);
    }//GEN-LAST:event_RegisterbtnActionPerformed

    private void HomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebtnActionPerformed
        // TODO add your handling code here:
        jSplitPane.setRightComponent(jRightPanel);
    }//GEN-LAST:event_HomebtnActionPerformed

    private void RefreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbtnActionPerformed
        // TODO add your handling code here:
        MainFrame mainframe = new MainFrame();
        mainframe.show();
        dispose();
    }//GEN-LAST:event_RefreshbtnActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void backroundbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backroundbtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "1) WELCOME TO OUR FOOD DELIVERY APPLICATION");
        
    }//GEN-LAST:event_backroundbtnActionPerformed

    private void AboutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutbtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)jRightPanel.getLayout();
        AboutUsPanel aup = new AboutUsPanel(userProcessContainer);
        //userProcessContainer.add("RegisterPanel", rp);
        //layout.next(userProcessContainer);
        jSplitPane.setRightComponent(aup);
    }//GEN-LAST:event_AboutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aboutbtn;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton Homebtn;
    private javax.swing.JPanel JLeftPanel;
    private javax.swing.JButton Loginbtn;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JLabel MainHeadinglbl;
    private javax.swing.JLabel Passwordlbl;
    private javax.swing.JPasswordField Passwordtxt;
    private javax.swing.JButton Refreshbtn;
    private javax.swing.JButton Registerbtn;
    private javax.swing.JLabel Usernamelbl;
    private javax.swing.JTextField Usernametxt;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JLabel Welcomelbl;
    private javax.swing.JButton backroundbtn;
    private javax.swing.JPanel jRightPanel;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel txtNewuser;
    // End of variables declaration//GEN-END:variables
}
