/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Business.Customer.CustomerDirectory;
import Business.DB4OUtil.DB4OUtil;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import UserInterface.CustomerRole.RegisterPanel;
import UserInterface.RestaurantAdminRole.AdminWorkAreaPanel;
import UserInterface.SystemAdminWorkArea.ManageCustomers;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author srikr
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private UserAccount userAccount;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    RestaurantDirectory restaurantDirectory; 
    CustomerDirectory customerDirectory;
    DeliveryManDirectory deliveryManDirectory;
    JPanel userProcessContainer;
    
    public MainFrame() {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        system = dB4OUtil.retrieveSystem();
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
        //this.setSize(1000, 650);
        restaurantDirectory = new RestaurantDirectory();
        customerDirectory = new CustomerDirectory();
        deliveryManDirectory = new DeliveryManDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        JLeftPanel = new javax.swing.JPanel();
        Usernamelbl = new javax.swing.JLabel();
        Usernametxt = new javax.swing.JTextField();
        Passwordlbl = new javax.swing.JLabel();
        Passwordtxt = new javax.swing.JPasswordField();
        Loginbtn = new javax.swing.JButton();
        Logoutbtn = new javax.swing.JButton();
        Registerbtn = new javax.swing.JButton();
        txtNewuser = new javax.swing.JLabel();
        Homebtn = new javax.swing.JButton();
        Refreshbtn = new javax.swing.JButton();
        Exitbtn = new javax.swing.JButton();
        jRightPanel = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        MainHeadinglbl = new javax.swing.JLabel();
        Welcomelbl = new javax.swing.JLabel();
        btn1ststep = new javax.swing.JButton();
        btn2ndstep = new javax.swing.JButton();
        btn3rdstep = new javax.swing.JButton();
        btn4thstep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLeftPanel.setBackground(new java.awt.Color(255, 255, 153));

        Usernamelbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Usernamelbl.setText("User Name");

        Passwordlbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Passwordlbl.setText("Password");

        Loginbtn.setBackground(new java.awt.Color(0, 0, 0));
        Loginbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        Loginbtn.setText("Login");
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnActionPerformed(evt);
            }
        });

        Logoutbtn.setBackground(new java.awt.Color(0, 0, 0));
        Logoutbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        Logoutbtn.setText("Logout");
        Logoutbtn.setEnabled(false);
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });

        Registerbtn.setBackground(new java.awt.Color(0, 0, 0));
        Registerbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        Registerbtn.setText("Register");
        Registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbtnActionPerformed(evt);
            }
        });

        txtNewuser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNewuser.setText("NEW USER?");

        Homebtn.setBackground(new java.awt.Color(0, 0, 0));
        Homebtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Homebtn.setForeground(new java.awt.Color(255, 255, 255));
        Homebtn.setText("Home");
        Homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebtnActionPerformed(evt);
            }
        });

        Refreshbtn.setBackground(new java.awt.Color(0, 0, 0));
        Refreshbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Refreshbtn.setForeground(new java.awt.Color(255, 255, 255));
        Refreshbtn.setText("Refresh");
        Refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbtnActionPerformed(evt);
            }
        });

        Exitbtn.setBackground(new java.awt.Color(0, 0, 0));
        Exitbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        Exitbtn.setText("Exit");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JLeftPanelLayout = new javax.swing.GroupLayout(JLeftPanel);
        JLeftPanel.setLayout(JLeftPanelLayout);
        JLeftPanelLayout.setHorizontalGroup(
            JLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Usernametxt)
            .addComponent(Passwordtxt)
            .addGroup(JLeftPanelLayout.createSequentialGroup()
                .addGroup(JLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Passwordlbl)
                    .addComponent(Usernamelbl)
                    .addComponent(Loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewuser)
                    .addComponent(Refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        JLeftPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Passwordlbl, txtNewuser});

        JLeftPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Homebtn, Loginbtn, Logoutbtn, Registerbtn});

        JLeftPanelLayout.setVerticalGroup(
            JLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLeftPanelLayout.createSequentialGroup()
                .addComponent(Homebtn)
                .addGap(106, 106, 106)
                .addComponent(Usernamelbl)
                .addGap(6, 6, 6)
                .addComponent(Usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Passwordlbl)
                .addGap(6, 6, 6)
                .addComponent(Passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Loginbtn)
                .addGap(12, 12, 12)
                .addComponent(Logoutbtn)
                .addGap(30, 30, 30)
                .addComponent(txtNewuser)
                .addGap(6, 6, 6)
                .addComponent(Registerbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(Refreshbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exitbtn))
        );

        JLeftPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Homebtn, Loginbtn, Logoutbtn, Registerbtn});

        JLeftPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Passwordlbl, txtNewuser});

        jSplitPane.setLeftComponent(JLeftPanel);

        jRightPanel.setBackground(new java.awt.Color(255, 255, 153));
        jRightPanel.setLayout(new java.awt.CardLayout());

        WelcomePanel.setBackground(new java.awt.Color(255, 255, 153));

        MainHeadinglbl.setBackground(new java.awt.Color(255, 255, 153));
        MainHeadinglbl.setFont(new java.awt.Font("Onyx", 1, 90)); // NOI18N
        MainHeadinglbl.setText("SHARE TO EAT");

        Welcomelbl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Welcomelbl.setText("WELCOME");

        btn1ststep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4.png"))); // NOI18N
        btn1ststep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ststepActionPerformed(evt);
            }
        });

        btn2ndstep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.jpg"))); // NOI18N
        btn2ndstep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ndstepActionPerformed(evt);
            }
        });

        btn3rdstep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.jpg"))); // NOI18N
        btn3rdstep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3rdstepActionPerformed(evt);
            }
        });

        btn4thstep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3.jpg"))); // NOI18N
        btn4thstep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4thstepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(497, 497, 497)
                        .addComponent(MainHeadinglbl))
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn3rdstep)
                            .addComponent(btn1ststep, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(180, 180, 180)
                        .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn4thstep)
                            .addComponent(btn2ndstep, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(581, 581, 581)
                        .addComponent(Welcomelbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        WelcomePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn1ststep, btn2ndstep, btn3rdstep, btn4thstep});

        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(MainHeadinglbl)
                .addGap(18, 18, 18)
                .addComponent(Welcomelbl)
                .addGap(40, 40, 40)
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2ndstep, javax.swing.GroupLayout.PREFERRED_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(btn1ststep, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn3rdstep)
                    .addComponent(btn4thstep))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        WelcomePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn1ststep, btn2ndstep, btn3rdstep, btn4thstep});

        jRightPanel.add(WelcomePanel, "card2");

        jSplitPane.setRightComponent(jRightPanel);

        getContentPane().add(jSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed
        // Get user name
        String userName = Usernametxt.getText();
        char[] passwordCharArray = Passwordtxt.getPassword();
        String password = String.valueOf(passwordCharArray);

        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);

        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }else{
            CardLayout layout = (CardLayout)jRightPanel.getLayout();
            jRightPanel.add("workArea",userAccount.getRole().createWorkArea(jRightPanel, userAccount, system));
            layout.next(jRightPanel);
        }

        Loginbtn.setEnabled(false);
        Logoutbtn.setEnabled(true);
        Usernametxt.setEnabled(false);
        Passwordtxt.setEnabled(false);
    }//GEN-LAST:event_LoginbtnActionPerformed

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        Logoutbtn.setEnabled(false);
        Usernametxt.setEnabled(true);
        Passwordtxt.setEnabled(true);
        Loginbtn.setEnabled(true);

        Usernametxt.setText("");
        Passwordtxt.setText("");

        jRightPanel.removeAll();
        MainFrame mainframe = new MainFrame();
        mainframe.show();
        dispose();
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void RegisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)jRightPanel.getLayout();
        RegisterPanel rp = new RegisterPanel(userProcessContainer, system);
        //userProcessContainer.add("RegisterPanel", rp);
        //layout.next(userProcessContainer);
        jSplitPane.setRightComponent(rp);
    }//GEN-LAST:event_RegisterbtnActionPerformed

    private void HomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebtnActionPerformed
        // TODO add your handling code here:
        jSplitPane.setRightComponent(jRightPanel);
    }//GEN-LAST:event_HomebtnActionPerformed

    private void RefreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbtnActionPerformed
        // TODO add your handling code here:
        MainFrame mainframe = new MainFrame();
        mainframe.show();
        dispose();
    }//GEN-LAST:event_RefreshbtnActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void btn1ststepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ststepActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "1) WELCOME TO OUR FOOD DELIVERY APPLICATION");
        
    }//GEN-LAST:event_btn1ststepActionPerformed

    private void btn2ndstepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ndstepActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "2) ADD DISHES AND ORDER");
    }//GEN-LAST:event_btn2ndstepActionPerformed

    private void btn3rdstepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3rdstepActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "3) WAIT FOR YOUR FAST DELIVERY");
    }//GEN-LAST:event_btn3rdstepActionPerformed

    private void btn4thstepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4thstepActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "4) HAVE A GOOD MEAL");
    }//GEN-LAST:event_btn4thstepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton Homebtn;
    private javax.swing.JPanel JLeftPanel;
    private javax.swing.JButton Loginbtn;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JLabel MainHeadinglbl;
    private javax.swing.JLabel Passwordlbl;
    private javax.swing.JPasswordField Passwordtxt;
    private javax.swing.JButton Refreshbtn;
    private javax.swing.JButton Registerbtn;
    private javax.swing.JLabel Usernamelbl;
    private javax.swing.JTextField Usernametxt;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JLabel Welcomelbl;
    private javax.swing.JButton btn1ststep;
    private javax.swing.JButton btn2ndstep;
    private javax.swing.JButton btn3rdstep;
    private javax.swing.JButton btn4thstep;
    private javax.swing.JPanel jRightPanel;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel txtNewuser;
    // End of variables declaration//GEN-END:variables
}
