/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author srikr
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private EcoSystem system;
    public MainFrame() {
        initComponents();
        this.setSize(1000, 650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        JLeftPanel = new javax.swing.JPanel();
        Usernamelbl = new javax.swing.JLabel();
        Usernametxt = new javax.swing.JTextField();
        Passwordlbl = new javax.swing.JLabel();
        Passwordtxt = new javax.swing.JPasswordField();
        Loginbtn = new javax.swing.JButton();
        Logoutbtn = new javax.swing.JButton();
        jRightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Usernamelbl.setText("User Name");

        Passwordlbl.setText("Password");

        Loginbtn.setText("Login");
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnActionPerformed(evt);
            }
        });

        Logoutbtn.setText("Logout");
        Logoutbtn.setEnabled(false);
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JLeftPanelLayout = new javax.swing.GroupLayout(JLeftPanel);
        JLeftPanel.setLayout(JLeftPanelLayout);
        JLeftPanelLayout.setHorizontalGroup(
            JLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLeftPanelLayout.createSequentialGroup()
                .addGroup(JLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JLeftPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Passwordtxt)
                            .addComponent(Usernametxt)))
                    .addGroup(JLeftPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(JLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Usernamelbl)
                            .addComponent(Passwordlbl))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(JLeftPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(JLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        JLeftPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Loginbtn, Logoutbtn});

        JLeftPanelLayout.setVerticalGroup(
            JLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLeftPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(Usernamelbl)
                .addGap(12, 12, 12)
                .addComponent(Usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Passwordlbl)
                .addGap(12, 12, 12)
                .addComponent(Passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Loginbtn)
                .addGap(27, 27, 27)
                .addComponent(Logoutbtn)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        JLeftPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Loginbtn, Logoutbtn});

        jSplitPane.setLeftComponent(JLeftPanel);

        javax.swing.GroupLayout jRightPanelLayout = new javax.swing.GroupLayout(jRightPanel);
        jRightPanel.setLayout(jRightPanelLayout);
        jRightPanelLayout.setHorizontalGroup(
            jRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        jRightPanelLayout.setVerticalGroup(
            jRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(jRightPanel);

        getContentPane().add(jSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed
        // Get user name
        String userName = Usernametxt.getText();
        char[] passwordCharArray = Passwordtxt.getPassword();
        String password = String.valueOf(passwordCharArray);

        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);

        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }else{
            CardLayout layout = (CardLayout)jRightPanel.getLayout();
            //jRightPanel.add("workArea",userAccount.getRole().createWorkArea(jRightPanel, userAccount, system));
            layout.next(jRightPanel);
        }

        Loginbtn.setEnabled(false);
        Logoutbtn.setEnabled(true);
        Usernametxt.setEnabled(false);
        Passwordtxt.setEnabled(false);
    }//GEN-LAST:event_LoginbtnActionPerformed

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        Logoutbtn.setEnabled(false);
        Usernametxt.setEnabled(true);
        Passwordtxt.setEnabled(true);
        Loginbtn.setEnabled(true);

        Usernametxt.setText("");
        Passwordtxt.setText("");

        jRightPanel.removeAll();
        JPanel blankJP = new JPanel();
        jRightPanel.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) jRightPanel.getLayout();
        crdLyt.next(jRightPanel);
    }//GEN-LAST:event_LogoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JLeftPanel;
    private javax.swing.JButton Loginbtn;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JLabel Passwordlbl;
    private javax.swing.JPasswordField Passwordtxt;
    private javax.swing.JLabel Usernamelbl;
    private javax.swing.JTextField Usernametxt;
    private javax.swing.JPanel jRightPanel;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
